# Generated by Django 5.2.9 on 2025-12-08 18:36

import django.db.models.deletion
import django.utils.timezone
import mptt.fields
import shortuuid.main
import shortuuidfield.fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoMetadataTrackMixin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bitrate", models.IntegerField()),
                ("codec", models.CharField(max_length=100)),
                ("size", models.PositiveBigIntegerField()),
                ("duration", models.IntegerField()),
                ("language", models.CharField(max_length=100, null=True)),
                ("track_number", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="VideoMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_progressive", models.BooleanField()),
                ("is_fragmented", models.BooleanField()),
                ("has_moov", models.BooleanField()),
                ("has_IOD", models.BooleanField()),
                ("brands", models.CharField(max_length=100)),
                ("mime", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="AudioTrack",
            fields=[
                (
                    "videometadatatrackmixin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="website.videometadatatrackmixin",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("channel_count", models.IntegerField()),
                ("sample_rate", models.IntegerField()),
                ("sample_size", models.IntegerField()),
            ],
            bases=("website.videometadatatrackmixin",),
        ),
        migrations.CreateModel(
            name="SubtitleTrack",
            fields=[
                (
                    "videometadatatrackmixin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="website.videometadatatrackmixin",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            bases=("website.videometadatatrackmixin",),
        ),
        migrations.CreateModel(
            name="VideoTrack",
            fields=[
                (
                    "videometadatatrackmixin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="website.videometadatatrackmixin",
                    ),
                ),
                ("height", models.IntegerField()),
                ("width", models.IntegerField()),
                ("fps", models.IntegerField()),
            ],
            bases=("website.videometadatatrackmixin",),
        ),
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "discord_id",
                    models.CharField(max_length=19, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=50)),
                ("guild_id", models.CharField(max_length=19)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DiscordSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("auto_setup_complete", models.BooleanField(default=False)),
                ("category_id", models.CharField(max_length=19, null=True)),
                ("role_id", models.CharField(max_length=19, null=True)),
                ("guild_id", models.CharField(max_length=19, null=True)),
                ("attachment_name", models.CharField(max_length=20, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Folder",
            fields=[
                (
                    "id",
                    shortuuidfield.fields.ShortUUIDField(
                        blank=True,
                        default=shortuuid.main.ShortUUID.uuid,
                        editable=False,
                        max_length=22,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_modified_at", models.DateTimeField(auto_now_add=True)),
                ("inTrash", models.BooleanField(default=False)),
                ("inTrashSince", models.DateTimeField(null=True)),
                ("ready", models.BooleanField(default=True)),
                ("password", models.CharField(max_length=50, null=True)),
                ("autoLock", models.BooleanField(default=False)),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "lockFrom",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="website.folder",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subfolders",
                        to="website.folder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    shortuuidfield.fields.ShortUUIDField(
                        blank=True,
                        default=shortuuid.main.ShortUUID.uuid,
                        editable=False,
                        max_length=22,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("extension", models.CharField(max_length=20)),
                ("size", models.PositiveBigIntegerField()),
                ("mimetype", models.CharField(default="text/plain", max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Video", "Video"),
                            ("Audio", "Audio"),
                            ("Text", "Text"),
                            ("Document", "Document"),
                            ("Ebook", "Ebook"),
                            ("System", "System"),
                            ("Database", "Database"),
                            ("Archive", "Archive"),
                            ("Image", "Image"),
                            ("Executable", "Executable"),
                            ("Code", "Code"),
                            ("Raw image", "Raw image"),
                            ("Other", "Other"),
                        ],
                        default="text",
                        max_length=50,
                    ),
                ),
                ("inTrash", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_modified_at", models.DateTimeField(auto_now=True)),
                ("ready", models.BooleanField(default=False)),
                ("inTrashSince", models.DateTimeField(null=True)),
                ("key", models.BinaryField(null=True)),
                ("iv", models.BinaryField(null=True)),
                ("encryption_method", models.SmallIntegerField()),
                ("duration", models.IntegerField(null=True)),
                ("frontend_id", models.CharField(max_length=40, unique=True)),
                ("crc", models.BigIntegerField(null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="website.folder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Fragment",
            fields=[
                ("message_id", models.CharField(db_index=True, max_length=19)),
                (
                    "attachment_id",
                    models.CharField(db_index=True, max_length=19, unique=True),
                ),
                ("size", models.PositiveBigIntegerField()),
                ("object_id", models.BigIntegerField()),
                ("channel_id", models.CharField(db_index=True, max_length=19)),
                (
                    "id",
                    shortuuidfield.fields.ShortUUIDField(
                        blank=True,
                        default=shortuuid.main.ShortUUID.uuid,
                        editable=False,
                        max_length=22,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sequence", models.SmallIntegerField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("offset", models.PositiveBigIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(
                        limit_choices_to={"model__in": ("bot", "webhook")},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fragments",
                        to="website.file",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalBot",
            fields=[
                (
                    "id",
                    shortuuidfield.fields.ShortUUIDField(
                        blank=True,
                        db_index=True,
                        default=shortuuid.main.ShortUUID.uuid,
                        editable=False,
                        max_length=22,
                    ),
                ),
                ("discord_id", models.CharField(max_length=19)),
                ("primary", models.BooleanField(default=False)),
                ("token", models.CharField(max_length=150)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("name", models.CharField(max_length=50)),
                ("disabled", models.BooleanField(default=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical bot",
                "verbose_name_plural": "historical bots",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalDiscordSettings",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("auto_setup_complete", models.BooleanField(default=False)),
                ("category_id", models.CharField(max_length=19, null=True)),
                ("role_id", models.CharField(max_length=19, null=True)),
                ("guild_id", models.CharField(max_length=19, null=True)),
                ("attachment_name", models.CharField(max_length=20, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical discord settings",
                "verbose_name_plural": "historical discord settingss",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalFile",
            fields=[
                (
                    "id",
                    shortuuidfield.fields.ShortUUIDField(
                        blank=True,
                        db_index=True,
                        default=shortuuid.main.ShortUUID.uuid,
                        editable=False,
                        max_length=22,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("extension", models.CharField(max_length=20)),
                ("size", models.PositiveBigIntegerField()),
                ("mimetype", models.CharField(default="text/plain", max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Video", "Video"),
                            ("Audio", "Audio"),
                            ("Text", "Text"),
                            ("Document", "Document"),
                            ("Ebook", "Ebook"),
                            ("System", "System"),
                            ("Database", "Database"),
                            ("Archive", "Archive"),
                            ("Image", "Image"),
                            ("Executable", "Executable"),
                            ("Code", "Code"),
                            ("Raw image", "Raw image"),
                            ("Other", "Other"),
                        ],
                        default="text",
                        max_length=50,
                    ),
                ),
                ("inTrash", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("last_modified_at", models.DateTimeField(blank=True, editable=False)),
                ("ready", models.BooleanField(default=False)),
                ("inTrashSince", models.DateTimeField(null=True)),
                ("key", models.BinaryField(null=True)),
                ("iv", models.BinaryField(null=True)),
                ("encryption_method", models.SmallIntegerField()),
                ("duration", models.IntegerField(null=True)),
                ("frontend_id", models.CharField(db_index=True, max_length=40)),
                ("crc", models.BigIntegerField(null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="website.folder",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical file",
                "verbose_name_plural": "historical files",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalTag",
            fields=[
                (
                    "id",
                    shortuuidfield.fields.ShortUUIDField(
                        blank=True,
                        db_index=True,
                        default=shortuuid.main.ShortUUID.uuid,
                        editable=False,
                        max_length=22,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=20)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical tag",
                "verbose_name_plural": "historical tags",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalUserPerms",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("globalLock", models.BooleanField(default=False)),
                ("admin", models.BooleanField(default=False)),
                ("execute", models.BooleanField(default=False)),
                ("create", models.BooleanField(default=True)),
                ("modify", models.BooleanField(default=True)),
                ("lock", models.BooleanField(default=True)),
                ("delete", models.BooleanField(default=True)),
                ("share", models.BooleanField(default=True)),
                ("download", models.BooleanField(default=True)),
                ("read", models.BooleanField(default=True)),
                ("settings_modify", models.BooleanField(default=True)),
                ("discord_modify", models.BooleanField(default=True)),
                ("change_password", models.BooleanField(default=True)),
                ("reset_lock", models.BooleanField(default=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical user perms",
                "verbose_name_plural": "historical user permss",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalUserSettings",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("sorting_by", models.CharField(default="name", max_length=50)),
                ("sort_by_asc", models.BooleanField(default=False)),
                ("locale", models.CharField(default="en", max_length=20)),
                ("view_mode", models.CharField(default="width grid", max_length=20)),
                ("date_format", models.BooleanField(default=False)),
                ("hide_locked_folders", models.BooleanField(default=False)),
                ("concurrent_upload_requests", models.SmallIntegerField(default=4)),
                ("subfolders_in_shares", models.BooleanField(default=False)),
                ("encryption_method", models.SmallIntegerField(default=2)),
                ("keep_creation_timestamp", models.BooleanField(default=False)),
                ("popup_preview", models.BooleanField(default=False)),
                ("theme", models.CharField(default="dark", max_length=20)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical user settings",
                "verbose_name_plural": "historical user settingss",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalWebhook",
            fields=[
                ("discord_id", models.CharField(db_index=True, max_length=19)),
                ("url", models.URLField(max_length=150)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("guild_id", models.CharField(max_length=19)),
                ("name", models.CharField(max_length=50)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="website.channel",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical webhook",
                "verbose_name_plural": "historical webhooks",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Moment",
            fields=[
                ("message_id", models.CharField(db_index=True, max_length=19)),
                (
                    "attachment_id",
                    models.CharField(db_index=True, max_length=19, unique=True),
                ),
                ("size", models.PositiveBigIntegerField()),
                ("object_id", models.BigIntegerField()),
                ("channel_id", models.CharField(db_index=True, max_length=19)),
                (
                    "id",
                    shortuuidfield.fields.ShortUUIDField(
                        blank=True,
                        default=shortuuid.main.ShortUUID.uuid,
                        editable=False,
                        max_length=22,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("timestamp", models.IntegerField()),
                ("iv", models.BinaryField(null=True)),
                ("key", models.BinaryField(null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        limit_choices_to={"model__in": ("bot", "webhook")},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="website.file"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PerDeviceToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_hash", models.CharField(db_index=True, max_length=64)),
                ("device_name", models.CharField(max_length=50)),
                (
                    "device_id",
                    shortuuidfield.fields.ShortUUIDField(
                        blank=True,
                        db_index=True,
                        default=shortuuid.main.ShortUUID.uuid,
                        editable=False,
                        max_length=22,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(null=True)),
                ("expires_at", models.DateTimeField()),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField()),
                ("country", models.CharField(max_length=50, null=True)),
                ("city", models.CharField(max_length=50, null=True)),
                (
                    "device_type",
                    models.CharField(
                        choices=[("mobile", "Mobile"), ("pc", "PC"), ("code", "Code")],
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Per-device token",
                "verbose_name_plural": "Per-device tokens",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Preview",
            fields=[
                ("message_id", models.CharField(db_index=True, max_length=19)),
                (
                    "attachment_id",
                    models.CharField(db_index=True, max_length=19, unique=True),
                ),
                ("size", models.PositiveBigIntegerField()),
                ("object_id", models.BigIntegerField()),
                ("channel_id", models.CharField(db_index=True, max_length=19)),
                (
                    "id",
                    shortuuidfield.fields.ShortUUIDField(
                        blank=True,
                        default=shortuuid.main.ShortUUID.uuid,
                        editable=False,
                        max_length=22,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("encrypted_size", models.PositiveBigIntegerField()),
                ("key", models.BinaryField()),
                ("iso", models.CharField(max_length=50, null=True)),
                ("aperture", models.CharField(max_length=50, null=True)),
                ("exposure_time", models.CharField(max_length=50, null=True)),
                ("model_name", models.CharField(max_length=50, null=True)),
                ("focal_length", models.CharField(max_length=50, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        limit_choices_to={"model__in": ("bot", "webhook")},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "file",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preview",
                        to="website.file",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShareableLink",
            fields=[
                (
                    "id",
                    shortuuidfield.fields.ShortUUIDField(
                        blank=True,
                        default=shortuuid.main.ShortUUID.uuid,
                        editable=False,
                        max_length=22,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token", models.CharField(max_length=255, unique=True)),
                ("expiration_time", models.DateTimeField()),
                ("password", models.TextField(max_length=100, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("object_id", models.CharField(max_length=22)),
                (
                    "content_type",
                    models.ForeignKey(
                        limit_choices_to={"model__in": ("folder", "file")},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShareAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.GenericIPAddressField(null=True)),
                ("user_agent", models.TextField()),
                ("access_time", models.DateTimeField(auto_now_add=True)),
                (
                    "accessed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "share",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.shareablelink",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShareAccessEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("event_type", models.CharField(max_length=64)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "access",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="website.shareaccess",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subtitle",
            fields=[
                ("message_id", models.CharField(db_index=True, max_length=19)),
                (
                    "attachment_id",
                    models.CharField(db_index=True, max_length=19, unique=True),
                ),
                ("size", models.PositiveBigIntegerField()),
                ("object_id", models.BigIntegerField()),
                ("channel_id", models.CharField(db_index=True, max_length=19)),
                (
                    "id",
                    shortuuidfield.fields.ShortUUIDField(
                        blank=True,
                        default=shortuuid.main.ShortUUID.uuid,
                        editable=False,
                        max_length=22,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("language", models.CharField(max_length=20)),
                ("iv", models.BinaryField(null=True)),
                ("key", models.BinaryField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("forced", models.BooleanField(default=False)),
                (
                    "content_type",
                    models.ForeignKey(
                        limit_choices_to={"model__in": ("bot", "webhook")},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtitles",
                        to="website.file",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    shortuuidfield.fields.ShortUUIDField(
                        blank=True,
                        default=shortuuid.main.ShortUUID.uuid,
                        editable=False,
                        max_length=22,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="file",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="files", to="website.tag"
            ),
        ),
        migrations.CreateModel(
            name="Thumbnail",
            fields=[
                ("message_id", models.CharField(db_index=True, max_length=19)),
                (
                    "attachment_id",
                    models.CharField(db_index=True, max_length=19, unique=True),
                ),
                ("size", models.PositiveBigIntegerField()),
                ("object_id", models.BigIntegerField()),
                ("channel_id", models.CharField(db_index=True, max_length=19)),
                (
                    "id",
                    shortuuidfield.fields.ShortUUIDField(
                        blank=True,
                        default=shortuuid.main.ShortUUID.uuid,
                        editable=False,
                        max_length=22,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("iv", models.BinaryField(null=True)),
                ("key", models.BinaryField(null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        limit_choices_to={"model__in": ("bot", "webhook")},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "file",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="website.file"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserPerms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("globalLock", models.BooleanField(default=False)),
                ("admin", models.BooleanField(default=False)),
                ("execute", models.BooleanField(default=False)),
                ("create", models.BooleanField(default=True)),
                ("modify", models.BooleanField(default=True)),
                ("lock", models.BooleanField(default=True)),
                ("delete", models.BooleanField(default=True)),
                ("share", models.BooleanField(default=True)),
                ("download", models.BooleanField(default=True)),
                ("read", models.BooleanField(default=True)),
                ("settings_modify", models.BooleanField(default=True)),
                ("discord_modify", models.BooleanField(default=True)),
                ("change_password", models.BooleanField(default=True)),
                ("reset_lock", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sorting_by", models.CharField(default="name", max_length=50)),
                ("sort_by_asc", models.BooleanField(default=False)),
                ("locale", models.CharField(default="en", max_length=20)),
                ("view_mode", models.CharField(default="width grid", max_length=20)),
                ("date_format", models.BooleanField(default=False)),
                ("hide_locked_folders", models.BooleanField(default=False)),
                ("concurrent_upload_requests", models.SmallIntegerField(default=4)),
                ("subfolders_in_shares", models.BooleanField(default=False)),
                ("encryption_method", models.SmallIntegerField(default=2)),
                ("keep_creation_timestamp", models.BooleanField(default=False)),
                ("popup_preview", models.BooleanField(default=False)),
                ("theme", models.CharField(default="dark", max_length=20)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserZIP",
            fields=[
                (
                    "id",
                    shortuuidfield.fields.ShortUUIDField(
                        blank=True,
                        default=shortuuid.main.ShortUUID.uuid,
                        editable=False,
                        max_length=22,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("token", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "files",
                    models.ManyToManyField(related_name="user_zips", to="website.file"),
                ),
                (
                    "folders",
                    models.ManyToManyField(
                        related_name="user_zips", to="website.folder"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="videometadatatrackmixin",
            name="video_metadata",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tracks",
                to="website.videometadata",
            ),
        ),
        migrations.AddField(
            model_name="videometadata",
            name="file",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="website.file"
            ),
        ),
        migrations.CreateModel(
            name="VideoPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("timestamp", models.IntegerField(default=0)),
                (
                    "file",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="website.file"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Webhook",
            fields=[
                (
                    "discord_id",
                    models.CharField(max_length=19, primary_key=True, serialize=False),
                ),
                ("url", models.URLField(max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("guild_id", models.CharField(max_length=19)),
                ("name", models.CharField(max_length=50)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.channel",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bot",
            fields=[
                (
                    "id",
                    shortuuidfield.fields.ShortUUIDField(
                        blank=True,
                        default=shortuuid.main.ShortUUID.uuid,
                        editable=False,
                        max_length=22,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("discord_id", models.CharField(max_length=19)),
                ("primary", models.BooleanField(default=False)),
                ("token", models.CharField(max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=50)),
                ("disabled", models.BooleanField(default=False)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("token__exact", ""), _negated=True),
                        name="bot_token_not_empty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("discord_id__regex", "^[0-9]{17,19}$")),
                        name="bot_discord_id_snowflake_format",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("name__exact", ""), _negated=True),
                        name="bot_name_not_empty",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="channel",
            constraint=models.CheckConstraint(
                condition=models.Q(("name__exact", ""), _negated=True),
                name="channel_name_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="channel",
            constraint=models.CheckConstraint(
                condition=models.Q(("guild_id__regex", "^[0-9]{17,19}$")),
                name="channel_guild_id_snowflake_format",
            ),
        ),
        migrations.AddConstraint(
            model_name="channel",
            constraint=models.CheckConstraint(
                condition=models.Q(("discord_id__regex", "^[0-9]{17,19}$")),
                name="channel_discord_id_snowflake_format",
            ),
        ),
        migrations.AddConstraint(
            model_name="discordsettings",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("guild_id__exact", ""),
                    ("guild_id__regex", "^[0-9]{17,19}$"),
                    _connector="OR",
                ),
                name="discordsettings_guild_id_valid_or_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="discordsettings",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("category_id__exact", ""),
                    ("category_id__regex", "^[0-9]{17,19}$"),
                    _connector="OR",
                ),
                name="discordsettings_category_id_valid_or_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="discordsettings",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("role_id__exact", ""),
                    ("role_id__regex", "^[0-9]{17,19}$"),
                    _connector="OR",
                ),
                name="discordsettings_role_id_valid_or_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="discordsettings",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("auto_setup_complete", False),
                    models.Q(("guild_id__exact", ""), _negated=True),
                    _connector="OR",
                ),
                name="discordsettings_guild_id_required_when_setup_complete",
            ),
        ),
        migrations.AddConstraint(
            model_name="discordsettings",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("auto_setup_complete", False),
                    models.Q(("category_id__exact", ""), _negated=True),
                    _connector="OR",
                ),
                name="discordsettings_category_id_required_when_setup_complete",
            ),
        ),
        migrations.AddConstraint(
            model_name="discordsettings",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("auto_setup_complete", False),
                    models.Q(("role_id__exact", ""), _negated=True),
                    _connector="OR",
                ),
                name="discordsettings_role_id_required_when_setup_complete",
            ),
        ),
        migrations.AddConstraint(
            model_name="discordsettings",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("auto_setup_complete", False),
                    models.Q(("attachment_name__exact", ""), _negated=True),
                    _connector="OR",
                ),
                name="discordsettings_attachment_name_required_when_setup_complete",
            ),
        ),
        migrations.AddConstraint(
            model_name="folder",
            constraint=models.CheckConstraint(
                condition=models.Q(("name__regex", "^\\s*$"), _negated=True),
                name="folder_name_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="folder",
            constraint=models.CheckConstraint(
                condition=models.Q(("last_modified_at__gte", models.F("created_at"))),
                name="folder_last_modified_after_created",
            ),
        ),
        migrations.AddConstraint(
            model_name="folder",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("inTrash", False), ("inTrashSince__isnull", True)),
                    models.Q(("inTrash", True), ("inTrashSince__isnull", False)),
                    _connector="OR",
                ),
                name="folder_trash_consistent",
            ),
        ),
        migrations.AddConstraint(
            model_name="folder",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("lockFrom__isnull", True), ("password__isnull", True)),
                    models.Q(("lockFrom__isnull", False), ("password__isnull", False)),
                    _connector="OR",
                ),
                name="folder_lock_password_consistent",
            ),
        ),
        migrations.AddConstraint(
            model_name="folder",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("lockFrom__isnull", False), ("autoLock", False), _connector="OR"
                ),
                name="folder_autoLock_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="folder",
            constraint=models.CheckConstraint(
                condition=models.Q(("id", models.F("parent")), _negated=True),
                name="folder_parent_not_self",
            ),
        ),
        migrations.AddConstraint(
            model_name="fragment",
            constraint=models.CheckConstraint(
                condition=models.Q(("sequence__gt", 0)),
                name="fragment_sequence_greater_than_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="fragment",
            constraint=models.CheckConstraint(
                condition=models.Q(("offset__gte", 0)),
                name="fragment_offset_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="fragment",
            constraint=models.UniqueConstraint(
                fields=("file", "sequence"),
                name="fragment_fragment_unique_sequence_per_file",
            ),
        ),
        migrations.AddConstraint(
            model_name="fragment",
            constraint=models.UniqueConstraint(
                fields=("file", "offset"),
                name="fragment_fragment_unique_offset_per_file",
            ),
        ),
        migrations.AddConstraint(
            model_name="moment",
            constraint=models.UniqueConstraint(
                fields=("file", "timestamp"), name="moment_unique_file_timestamp"
            ),
        ),
        migrations.AddConstraint(
            model_name="moment",
            constraint=models.CheckConstraint(
                condition=models.Q(("timestamp__gte", 0)),
                name="moment_timestamp_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="moment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("key__isnull", True), ("iv__isnull", True)),
                    models.Q(("key__isnull", False), ("iv__isnull", False)),
                    _connector="OR",
                ),
                name="moment_iv_key_consistent",
            ),
        ),
        migrations.AddConstraint(
            model_name="perdevicetoken",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("device_type__in", ["mobile", "pc", "code"]),
                    ("device_type__isnull", True),
                    _connector="OR",
                ),
                name="valid_device_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="perdevicetoken",
            constraint=models.CheckConstraint(
                condition=models.Q(("token_hash__exact", ""), _negated=True),
                name="perdevicetoken_token_hash_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="perdevicetoken",
            constraint=models.CheckConstraint(
                condition=models.Q(("device_id__exact", ""), _negated=True),
                name="perdevicetoken_device_id_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="perdevicetoken",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("expires_at__isnull", True),
                    ("expires_at__gte", models.F("created_at")),
                    _connector="OR",
                ),
                name="perdevicetoken_expires_after_created",
            ),
        ),
        migrations.AddConstraint(
            model_name="perdevicetoken",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("last_used_at__isnull", True),
                    ("last_used_at__gte", models.F("created_at")),
                    _connector="OR",
                ),
                name="perdevicetoken_last_used_after_created",
            ),
        ),
        migrations.AddConstraint(
            model_name="perdevicetoken",
            constraint=models.UniqueConstraint(
                fields=("user", "device_id"),
                name="perdevicetoken_unique_device_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="perdevicetoken",
            constraint=models.UniqueConstraint(
                fields=("user", "token_hash"),
                name="perdevicetoken_unique_token_hash_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="preview",
            constraint=models.CheckConstraint(
                condition=models.Q(("encrypted_size__gte", 0)),
                name="preview_encrypted_size_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="preview",
            constraint=models.CheckConstraint(
                condition=models.Q(("key__isnull", False)), name="preview_key_required"
            ),
        ),
        migrations.AddConstraint(
            model_name="shareablelink",
            constraint=models.CheckConstraint(
                condition=models.Q(("token__exact", ""), _negated=True),
                name="shareablelink_token_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="shareablelink",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("password__isnull", True),
                    models.Q(("password__exact", ""), _negated=True),
                    _connector="OR",
                ),
                name="shareablelink_password_not_empty_string",
            ),
        ),
        migrations.AddIndex(
            model_name="shareaccessevent",
            index=models.Index(
                fields=["event_type"], name="website_sha_event_t_a677ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shareaccessevent",
            index=models.Index(
                fields=["timestamp"], name="website_sha_timesta_962bb2_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="subtitle",
            constraint=models.CheckConstraint(
                condition=models.Q(("language__exact", ""), _negated=True),
                name="subtitle_language_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="subtitle",
            constraint=models.UniqueConstraint(
                fields=("file", "language"), name="subtitle_unique_language_per_file"
            ),
        ),
        migrations.AddConstraint(
            model_name="subtitle",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("key__isnull", True), ("iv__isnull", True)),
                    models.Q(("key__isnull", False), ("iv__isnull", False)),
                    _connector="OR",
                ),
                name="subtitle_encryption_fields_consistent",
            ),
        ),
        migrations.AddConstraint(
            model_name="file",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "type__in",
                        [
                            "Video",
                            "Audio",
                            "Text",
                            "Document",
                            "Ebook",
                            "System",
                            "Database",
                            "Archive",
                            "Image",
                            "Executable",
                            "Code",
                            "Raw image",
                            "Other",
                        ],
                    )
                ),
                name="file_valid_file_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="file",
            constraint=models.CheckConstraint(
                condition=models.Q(("size__gte", 0)), name="file_size_non_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="file",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("duration__gte", 0), ("duration__isnull", True), _connector="OR"
                ),
                name="file_duration_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="file",
            constraint=models.CheckConstraint(
                condition=models.Q(("name__exact", ""), _negated=True),
                name="file_name_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="file",
            constraint=models.CheckConstraint(
                condition=models.Q(("extension__exact", ""), _negated=True),
                name="file_extension_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="file",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("encryption_method", 0),
                        ("key__isnull", True),
                        ("iv__isnull", True),
                    ),
                    models.Q(
                        ("encryption_method__gt", 0),
                        ("key__isnull", False),
                        ("iv__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="file_encryption_fields_consistent",
            ),
        ),
        migrations.AddConstraint(
            model_name="file",
            constraint=models.CheckConstraint(
                condition=models.Q(("last_modified_at__gte", models.F("created_at"))),
                name="file_last_modified_after_created",
            ),
        ),
        migrations.AddConstraint(
            model_name="file",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("crc__gte", 0), ("crc__isnull", True), _connector="OR"
                ),
                name="file_crc_non_negative_or_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="file",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("crc", 0), ("size__lte", 0)),
                    models.Q(("crc__gt", 0), ("size__gt", 0)),
                    ("crc__isnull", True),
                    _connector="OR",
                ),
                name="file_crc_valid_based_on_size",
            ),
        ),
        migrations.AddConstraint(
            model_name="thumbnail",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("iv__isnull", True), ("key__isnull", True)),
                    models.Q(("iv__isnull", False), ("key__isnull", False)),
                    _connector="OR",
                ),
                name="thumbnail_iv_key_consistent",
            ),
        ),
        migrations.AddConstraint(
            model_name="videoposition",
            constraint=models.CheckConstraint(
                condition=models.Q(("timestamp__gte", 0)),
                name="videoposition_timestamp_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="webhook",
            constraint=models.CheckConstraint(
                condition=models.Q(("discord_id__exact", ""), _negated=True),
                name="webhook_discord_id_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="webhook",
            constraint=models.CheckConstraint(
                condition=models.Q(("url__exact", ""), _negated=True),
                name="webhook_url_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="webhook",
            constraint=models.CheckConstraint(
                condition=models.Q(("guild_id__regex", "^[0-9]{17,19}$")),
                name="webhook_guild_id_snowflake_format",
            ),
        ),
        migrations.AddConstraint(
            model_name="webhook",
            constraint=models.CheckConstraint(
                condition=models.Q(("discord_id__regex", "^[0-9]{17,19}$")),
                name="webhook_discord_id_snowflake_format",
            ),
        ),
        migrations.AddConstraint(
            model_name="webhook",
            constraint=models.CheckConstraint(
                condition=models.Q(("name__exact", ""), _negated=True),
                name="webhook_name_not_empty",
            ),
        ),
    ]
