# Generated by Django 4.2.16 on 2024-11-02 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import shortuuid.main
import shortuuidfield.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    shortuuidfield.fields.ShortUUIDField(
                        blank=True,
                        default=shortuuid.main.ShortUUID.uuid,
                        editable=False,
                        max_length=22,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField(max_length=255)),
                ("extension", models.CharField(max_length=10)),
                ("streamable", models.BooleanField(default=False)),
                ("size", models.PositiveBigIntegerField()),
                ("mimetype", models.CharField(default="text/plain", max_length=15)),
                ("type", models.CharField(default="text", max_length=15)),
                ("inTrash", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "last_modified_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("ready", models.BooleanField(default=False)),
                ("inTrashSince", models.DateTimeField(blank=True, null=True)),
                ("autoLock", models.BooleanField(default=False)),
                ("password", models.CharField(blank=True, max_length=255, null=True)),
                ("key", models.BinaryField()),
                ("iv", models.BinaryField(null=True)),
                ("webhook", models.TextField()),
                ("encryption_method", models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Folder",
            fields=[
                (
                    "id",
                    shortuuidfield.fields.ShortUUIDField(
                        blank=True,
                        default=shortuuid.main.ShortUUID.uuid,
                        editable=False,
                        max_length=22,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField(max_length=255)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "last_modified_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("inTrash", models.BooleanField(default=False)),
                ("inTrashSince", models.DateTimeField(blank=True, null=True)),
                ("password", models.CharField(blank=True, max_length=255, null=True)),
                ("autoLock", models.BooleanField(default=False)),
                ("ready", models.BooleanField(default=True)),
                (
                    "lockFrom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="website.folder",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subfolders",
                        to="website.folder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VideoPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("timestamp", models.IntegerField(default=0)),
                (
                    "file",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="website.file"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserZIP",
            fields=[
                (
                    "id",
                    shortuuidfield.fields.ShortUUIDField(
                        blank=True,
                        default=shortuuid.main.ShortUUID.uuid,
                        editable=False,
                        max_length=22,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("token", models.CharField(blank=True, max_length=255, unique=True)),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "files",
                    models.ManyToManyField(
                        blank=True, related_name="user_zips", to="website.file"
                    ),
                ),
                (
                    "folders",
                    models.ManyToManyField(
                        blank=True, related_name="user_zips", to="website.folder"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sorting_by", models.TextField(default="name", max_length=50)),
                ("sort_by_asc", models.BooleanField(default=False)),
                ("locale", models.TextField(default="en", max_length=50)),
                (
                    "view_mode",
                    models.TextField(default="mosaic gallery", max_length=50),
                ),
                ("date_format", models.BooleanField(default=False)),
                ("hide_locked_folders", models.BooleanField(default=False)),
                ("concurrent_upload_requests", models.SmallIntegerField(default=4)),
                ("subfolders_in_shares", models.BooleanField(default=False)),
                ("discord_webhook", models.TextField(null=True)),
                ("encryption_method", models.SmallIntegerField(default=1)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserPerms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("globalLock", models.BooleanField(default=False)),
                ("admin", models.BooleanField(default=False)),
                ("execute", models.BooleanField(default=False)),
                ("create", models.BooleanField(default=True)),
                ("modify", models.BooleanField(default=True)),
                ("lock", models.BooleanField(default=True)),
                ("delete", models.BooleanField(default=True)),
                ("share", models.BooleanField(default=True)),
                ("download", models.BooleanField(default=True)),
                ("read", models.BooleanField(default=True)),
                ("settings_modify", models.BooleanField(default=True)),
                ("change_password", models.BooleanField(default=True)),
                ("reset_lock", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Thumbnail",
            fields=[
                (
                    "id",
                    shortuuidfield.fields.ShortUUIDField(
                        blank=True,
                        default=shortuuid.main.ShortUUID.uuid,
                        editable=False,
                        max_length=22,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("size", models.PositiveBigIntegerField()),
                ("attachment_id", models.CharField(max_length=255)),
                ("message_id", models.CharField(max_length=255)),
                ("iv", models.BinaryField(null=True)),
                ("key", models.BinaryField(null=True)),
                (
                    "file",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="website.file"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShareableLink",
            fields=[
                (
                    "id",
                    shortuuidfield.fields.ShortUUIDField(
                        blank=True,
                        default=shortuuid.main.ShortUUID.uuid,
                        editable=False,
                        max_length=22,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token", models.CharField(max_length=255, unique=True)),
                ("expiration_time", models.DateTimeField()),
                ("password", models.TextField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("object_id", models.CharField(max_length=22)),
                (
                    "content_type",
                    models.ForeignKey(
                        limit_choices_to={"model__in": ("folder", "file")},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Preview",
            fields=[
                (
                    "id",
                    shortuuidfield.fields.ShortUUIDField(
                        blank=True,
                        default=shortuuid.main.ShortUUID.uuid,
                        editable=False,
                        max_length=22,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("size", models.PositiveBigIntegerField()),
                ("encrypted_size", models.PositiveBigIntegerField()),
                ("attachment_id", models.CharField(max_length=255, null=True)),
                ("message_id", models.CharField(max_length=255)),
                ("key", models.BinaryField()),
                ("iso", models.CharField(max_length=50, null=True)),
                ("aperture", models.CharField(max_length=50, null=True)),
                ("exposure_time", models.CharField(max_length=50, null=True)),
                ("model_name", models.CharField(max_length=50, null=True)),
                ("focal_length", models.CharField(max_length=50, null=True)),
                (
                    "file",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="website.file"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Fragment",
            fields=[
                ("sequence", models.SmallIntegerField()),
                (
                    "id",
                    shortuuidfield.fields.ShortUUIDField(
                        blank=True,
                        default=shortuuid.main.ShortUUID.uuid,
                        editable=False,
                        max_length=22,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("message_id", models.CharField(max_length=255)),
                ("size", models.PositiveBigIntegerField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("attachment_id", models.CharField(max_length=255, null=True)),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fragments",
                        to="website.file",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="file",
            name="lockFrom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="website.folder",
            ),
        ),
        migrations.AddField(
            model_name="file",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="file",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="website.folder",
            ),
        ),
    ]
