# Generated by Django 5.2.9 on 2026-03-19 21:37

import shortuuid.main
import shortuuidfield.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("website", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="file",
            name="file_valid_state",
        ),
        migrations.RemoveConstraint(
            model_name="folder",
            name="folder_valid_state",
        ),
        migrations.RemoveConstraint(
            model_name="folder",
            name="folder_autoLock_valid",
        ),
        migrations.RemoveConstraint(
            model_name="fragment",
            name="fragment_valid_state",
        ),
        migrations.AlterField(
            model_name="bot",
            name="id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="state",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("deleting", "Deleting"),
                    ("deleted", "Deleted"),
                ],
                db_index=True,
                default="active",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="folder",
            name="id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="folder",
            name="state",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("deleting", "Deleting"),
                    ("deleted", "Deleted"),
                ],
                db_index=True,
                default="active",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="fragment",
            name="id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="fragment",
            name="state",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("deleting", "Deleting"),
                    ("deleted", "Deleted"),
                ],
                db_index=True,
                default="active",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="historicalbot",
            name="id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                db_index=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
            ),
        ),
        migrations.AlterField(
            model_name="historicalfile",
            name="id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                db_index=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
            ),
        ),
        migrations.AlterField(
            model_name="historicalfile",
            name="state",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("deleting", "Deleting"),
                    ("deleted", "Deleted"),
                ],
                db_index=True,
                default="active",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="historicaltag",
            name="id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                db_index=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
            ),
        ),
        migrations.AlterField(
            model_name="moment",
            name="id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="perdevicetoken",
            name="device_id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                db_index=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="shareablelink",
            name="id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="shareaccess",
            name="id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="shareaccessevent",
            name="id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="subtitle",
            name="id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="thumbnail",
            name="id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="userzip",
            name="id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="file",
            constraint=models.CheckConstraint(
                condition=models.Q(("state__in", ["active", "deleting", "deleted"])),
                name="file_valid_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="folder",
            constraint=models.CheckConstraint(
                condition=models.Q(("state__in", ["active", "deleting", "deleted"])),
                name="folder_valid_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="folder",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("lockFrom__isnull", False),
                    ("autoLock", False),
                    ("state", "deleting"),
                    _connector="OR",
                ),
                name="folder_autoLock_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="fragment",
            constraint=models.CheckConstraint(
                condition=models.Q(("state__in", ["active", "deleting", "deleted"])),
                name="fragment_valid_state",
            ),
        ),
    ]
