# Generated by Django 5.2.9 on 2025-12-21 00:47

import django.db.models.deletion
import shortuuid.main
import shortuuidfield.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("website", "0002_remove_bot_disabled_remove_file_mimetype_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttachmentLinker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("message_id", models.CharField(db_index=True, max_length=19)),
                ("object_id", models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="FragmentLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveIntegerField()),
            ],
            options={
                "ordering": ["sequence"],
            },
        ),
        migrations.CreateModel(
            name="ThumbnailLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveIntegerField()),
            ],
            options={
                "ordering": ["sequence"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="file",
            name="file_valid_file_type",
        ),
        migrations.AlterField(
            model_name="bot",
            name="id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="type",
            field=models.CharField(
                choices=[
                    ("Video", "Video"),
                    ("Audio", "Audio"),
                    ("Image", "Image"),
                    ("Raw image", "Raw image"),
                    ("Text", "Text"),
                    ("Document", "Document"),
                    ("Ebook", "Ebook"),
                    ("System", "System"),
                    ("Database", "Database"),
                    ("Archive", "Archive"),
                    ("Executable", "Executable"),
                    ("Code", "Code"),
                    ("Other", "Other"),
                ],
                default="text",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="folder",
            name="id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="fragment",
            name="id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="historicalbot",
            name="id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                db_index=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
            ),
        ),
        migrations.AlterField(
            model_name="historicalfile",
            name="id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                db_index=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
            ),
        ),
        migrations.AlterField(
            model_name="historicalfile",
            name="type",
            field=models.CharField(
                choices=[
                    ("Video", "Video"),
                    ("Audio", "Audio"),
                    ("Image", "Image"),
                    ("Raw image", "Raw image"),
                    ("Text", "Text"),
                    ("Document", "Document"),
                    ("Ebook", "Ebook"),
                    ("System", "System"),
                    ("Database", "Database"),
                    ("Archive", "Archive"),
                    ("Executable", "Executable"),
                    ("Code", "Code"),
                    ("Other", "Other"),
                ],
                default="text",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="historicaltag",
            name="id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                db_index=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
            ),
        ),
        migrations.AlterField(
            model_name="moment",
            name="id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="perdevicetoken",
            name="device_id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                db_index=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="preview",
            name="id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="shareablelink",
            name="id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="subtitle",
            name="id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="thumbnail",
            name="id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="userzip",
            name="id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="file",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "type__in",
                        [
                            "Video",
                            "Audio",
                            "Image",
                            "Raw image",
                            "Text",
                            "Document",
                            "Ebook",
                            "System",
                            "Database",
                            "Archive",
                            "Executable",
                            "Code",
                            "Other",
                        ],
                    )
                ),
                name="file_valid_file_type",
            ),
        ),
        migrations.AddField(
            model_name="attachmentlinker",
            name="channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="website.channel"
            ),
        ),
        migrations.AddField(
            model_name="attachmentlinker",
            name="content_type",
            field=models.ForeignKey(
                limit_choices_to={"model__in": ("bot", "webhook")},
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="attachmentlinker",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="fragmentlink",
            name="fragment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="website.fragment"
            ),
        ),
        migrations.AddField(
            model_name="fragmentlink",
            name="linker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fragments",
                to="website.attachmentlinker",
            ),
        ),
        migrations.AddField(
            model_name="thumbnaillink",
            name="linker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="thumbnails",
                to="website.attachmentlinker",
            ),
        ),
        migrations.AddField(
            model_name="thumbnaillink",
            name="thumbnail",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="website.thumbnail"
            ),
        ),
        migrations.AddConstraint(
            model_name="fragmentlink",
            constraint=models.UniqueConstraint(
                fields=("linker", "sequence"),
                name="fragmentlink_unique_fragment_sequence_per_linker",
            ),
        ),
        migrations.AddConstraint(
            model_name="fragmentlink",
            constraint=models.UniqueConstraint(
                fields=("linker", "fragment"),
                name="fragmentlink_unique_fragment_per_linker",
            ),
        ),
        migrations.AddConstraint(
            model_name="fragmentlink",
            constraint=models.CheckConstraint(
                condition=models.Q(("sequence__gt", 0)),
                name="fragmentlink_sequence_gt_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="thumbnaillink",
            constraint=models.UniqueConstraint(
                fields=("linker", "sequence"),
                name="thumbnaillink_unique_thumbnail_sequence_per_linker",
            ),
        ),
        migrations.AddConstraint(
            model_name="thumbnaillink",
            constraint=models.UniqueConstraint(
                fields=("linker", "thumbnail"),
                name="thumbnaillink_unique_thumbnail_per_linker",
            ),
        ),
        migrations.AddConstraint(
            model_name="thumbnaillink",
            constraint=models.CheckConstraint(
                condition=models.Q(("sequence__gt", 0)),
                name="thumbnaillink_sequence_gt_0",
            ),
        ),
    ]
