# Generated by Django 4.2.18 on 2025-03-12 18:28

from django.db import migrations, models
import shortuuid.main
import shortuuidfield.fields


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0002_alter_file_id_alter_folder_id_alter_fragment_id_and_more"),
    ]

    operations = [

    ]
