# Generated by Django 5.2.9 on 2026-03-11 19:47

import shortuuid.main
import shortuuidfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0002_remove_historicaluserperms_history_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawmetadata",
            name="failed_to_process",
            field=models.BooleanField(default=False),
        )
    ]
