# Generated by Django 4.2.18 on 2025-01-30 10:55

from django.db import migrations

import uuid


def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model("website", "file")
    for row in MyModel.objects.all():
        row.frontend_id = uuid.uuid4()
        row.save(update_fields=["frontend_id"])

class Migration(migrations.Migration):
    dependencies = [
        ("website", "0003_file_frontend_id_historicalfile_frontend_id_and_more"),
    ]

    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
