# Generated by Django 4.2.18 on 2025-01-30 10:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0004_auto_20250130_1155"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="frontend_id",
            field=models.CharField(default=uuid.uuid4, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="historicalfile",
            name="frontend_id",
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=20),
        ),
    ]
