# Generated by Django 4.2.18 on 2025-03-19 20:21

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.main
import shortuuidfield.fields


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0005_alter_file_id_alter_folder_id_alter_fragment_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isFragmented", models.BooleanField()),
                ("isProgressive", models.BooleanField()),
                ("hasMoov", models.BooleanField()),
                ("hasIOD", models.BooleanField()),
                ("brands", models.CharField(max_length=50)),
                ("mime", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="VideoMetadataTrackMixin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bitrate", models.IntegerField()),
                ("codec", models.CharField(max_length=50)),
                ("size", models.IntegerField()),
                ("duration", models.IntegerField()),
                ("language", models.CharField(max_length=50)),
                ("track_number", models.IntegerField()),
                (
                    "video_metadata",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata",
                        to="website.videometadata",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AudioTrack",
            fields=[
                (
                    "videometadatatrackmixin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="website.videometadatatrackmixin",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("channel_count", models.IntegerField()),
                ("sample_rate", models.IntegerField()),
                ("sample_size", models.IntegerField()),
            ],
            bases=("website.videometadatatrackmixin",),
        ),
        migrations.CreateModel(
            name="SubtitleTrack",
            fields=[
                (
                    "videometadatatrackmixin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="website.videometadatatrackmixin",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
            ],
            bases=("website.videometadatatrackmixin",),
        ),
        migrations.CreateModel(
            name="VideoTrack",
            fields=[
                (
                    "videometadatatrackmixin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="website.videometadatatrackmixin",
                    ),
                ),
                ("height", models.IntegerField()),
                ("width", models.IntegerField()),
                ("fps", models.IntegerField()),
            ],
            bases=("website.videometadatatrackmixin",),
        ),
        migrations.AddField(
            model_name="videometadata",
            name="file",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="website.file"
            ),
        ),
    ]
