# Generated by Django 6.0.4 on 2026-05-31 13:38

import django.db.models.deletion
import django.utils.timezone
import shortuuid.main
import shortuuidfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0005_alter_bot_id_alter_file_id_alter_folder_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RawExtractionClaim",
            fields=[
                (
                    "file",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="website.file",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("running", "Running"), ("failed", "Failed")],
                        default="running",
                        max_length=16,
                    ),
                ),
                ("claimed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("attempts", models.PositiveIntegerField(default=1)),
                ("last_error", models.TextField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["state", "claimed_at"],
                        name="website_raw_state_7f32be_idx",
                    ),
                    models.Index(
                        fields=["state", "attempts"],
                        name="website_raw_state_6c4294_idx",
                    ),
                ],
            },
        ),
    ]
