# Generated by Django 4.2.18 on 2025-01-30 10:53

from django.db import migrations, models
import shortuuid.main
import shortuuidfield.fields
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0006_alter_file_frontend_id_alter_file_id_alter_folder_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fragment",
            name="offset",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="historicalfragment",
            name="offset",
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
