# Generated by Django 4.2.18 on 2025-03-19 21:36

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.main
import shortuuidfield.fields


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0006_videometadata_videometadatatrackmixin_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="videometadata",
            old_name="hasIOD",
            new_name="has_IOD",
        ),
        migrations.RenameField(
            model_name="videometadata",
            old_name="hasMoov",
            new_name="has_moov",
        ),
        migrations.RenameField(
            model_name="videometadata",
            old_name="isFragmented",
            new_name="is_fragmented",
        ),
        migrations.RenameField(
            model_name="videometadata",
            old_name="isProgressive",
            new_name="is_progressive",
        ),
        migrations.AlterField(
            model_name="videometadatatrackmixin",
            name="language",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="videometadatatrackmixin",
            name="video_metadata",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tracks",
                to="website.videometadata",
            ),
        ),

    ]
