# Generated by Django 4.2.18 on 2025-01-30 15:38

from django.db import migrations

def gen_offset(apps, schema_editor):
    MyModel = apps.get_model("website", "fragment")
    for row in MyModel.objects.all():
        row.offset = (row.sequence - 1) * 10 * 1023 * 1024
        row.save(update_fields=["offset"])

    MyModel = apps.get_model("website", "historicalfragment")
    for row in MyModel.objects.all():
        row.offset = (row.sequence - 1) * 10 * 1023 * 1024
        row.save(update_fields=["offset"])

class Migration(migrations.Migration):
    dependencies = [
        ("website", "0007_add_fragment_offset"),
    ]

    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(gen_offset, reverse_code=migrations.RunPython.noop),
    ]
