# Generated by Django 4.2.18 on 2025-01-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0008_auto_20250130_1638"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fragment",
            name="offset",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="historicalfragment",
            name="offset",
            field=models.IntegerField(db_index=True),
        ),
    ]
