# Generated by Django 6.0.4 on 2026-06-14 17:23

import shortuuid.main
import shortuuidfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0008_notification_data_alter_bot_id_alter_file_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="client_side_decryption",
            field=models.BooleanField(default=True),
        )
    ]
