# Generated by Django 6.0.4 on 2026-07-07 17:25

from django.db import migrations, models
from django.db.models import Q

from website.models.other_models import NotificationKind

class Migration(migrations.Migration):
    dependencies = [
        ("website", "0010_remove_usersettings_client_side_decryption_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="notification",
            name="notification_kind_valid",
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.CheckConstraint(
                condition=Q(kind__in=NotificationKind.values),
                name="notification_kind_valid",
            ),
        ),
    ]