# Generated by Django 4.2.18 on 2025-07-02 19:37

from django.db import migrations, models
import shortuuid.main
import shortuuidfield.fields


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0010_normalize_file_types"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="file",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "type__in",
                        [
                            "Video",
                            "Audio",
                            "Text",
                            "Document",
                            "Ebook",
                            "System",
                            "Database",
                            "Archive",
                            "Image",
                            "Executable",
                            "Code",
                            "Raw image",
                            "Other",
                        ],
                    )
                ),
                name="valid_file_type",
            ),
        ),
    ]
