# Generated by Django 4.2.18 on 2025-07-10 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.main
import shortuuidfield.fields


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("website", "0011_add_file_type_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="primary",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="discordsettings",
            name="auto_setup_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="discordsettings",
            name="category_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="discordsettings",
            name="role_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="historicalbot",
            name="primary",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicaldiscordsettings",
            name="auto_setup_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicaldiscordsettings",
            name="category_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="historicaldiscordsettings",
            name="role_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.CreateModel(
            name="Channel",
            fields=[
                ("name", models.CharField(max_length=20)),
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("guild_id", models.CharField(blank=True, default="", max_length=100)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="historicalwebhook",
            name="channel_fk",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="website.channel",
            ),
        ),
        migrations.AddField(
            model_name="webhook",
            name="channel_fk",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="website.channel",
            ),
        ),
    ]
