# Generated by Django 4.2.18 on 2025-07-10 21:28

from django.db import migrations, models
import django.utils.timezone
import shortuuid.main
import shortuuidfield.fields


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0012_bot_primary_discordsettings_auto_setup_complete_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="discordsettings",
            name="channel_id",
        ),
        migrations.RemoveField(
            model_name="historicaldiscordsettings",
            name="channel_id",
        ),
        migrations.RemoveField(
            model_name="historicalusersettings",
            name="use_proxy",
        ),
        migrations.RemoveField(
            model_name="historicalwebhook",
            name="channel_id",
        ),
        migrations.RemoveField(
            model_name="usersettings",
            name="use_proxy",
        ),
        migrations.RemoveField(
            model_name="webhook",
            name="channel_id",
        ),
        migrations.AddField(
            model_name="channel",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
