# Generated by Django 4.2.18 on 2025-07-10 21:39

from django.db import migrations, models
import shortuuid.main
import shortuuidfield.fields


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0013_rename_channel_fk_historicalwebhook_channel_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalwebhook",
            old_name="channel_fk",
            new_name="channel",
        ),
        migrations.RenameField(
            model_name="webhook",
            old_name="channel_fk",
            new_name="channel",
        ),
    ]
