# Generated by Django 4.2.18 on 2025-07-10 21:46

from django.db import migrations, models
import shortuuid.main
import shortuuidfield.fields


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0014_rename_channel_fk_historicalwebhook_channel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="type",
            field=models.CharField(
                choices=[
                    ("Video", "Video"),
                    ("Audio", "Audio"),
                    ("Text", "Text"),
                    ("Document", "Document"),
                    ("Ebook", "Ebook"),
                    ("System", "System"),
                    ("Database", "Database"),
                    ("Archive", "Archive"),
                    ("Image", "Image"),
                    ("Executable", "Executable"),
                    ("Code", "Code"),
                    ("Raw image", "Raw image"),
                    ("Other", "Other"),
                ],
                default="text",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="folder",
            name="id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="fragment",
            name="attachment_id",
            field=models.CharField(
                db_index=True, max_length=32, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="fragment",
            name="id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="fragment",
            name="message_id",
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="historicalfile",
            name="id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                db_index=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
            ),
        ),
        migrations.AlterField(
            model_name="historicalfile",
            name="type",
            field=models.CharField(
                choices=[
                    ("Video", "Video"),
                    ("Audio", "Audio"),
                    ("Text", "Text"),
                    ("Document", "Document"),
                    ("Ebook", "Ebook"),
                    ("System", "System"),
                    ("Database", "Database"),
                    ("Archive", "Archive"),
                    ("Image", "Image"),
                    ("Executable", "Executable"),
                    ("Code", "Code"),
                    ("Raw image", "Raw image"),
                    ("Other", "Other"),
                ],
                default="text",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="historicalthumbnail",
            name="id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                db_index=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
            ),
        ),
        migrations.AlterField(
            model_name="historicalthumbnail",
            name="message_id",
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="moment",
            name="attachment_id",
            field=models.CharField(
                db_index=True, max_length=32, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="moment",
            name="message_id",
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="preview",
            name="attachment_id",
            field=models.CharField(
                db_index=True, max_length=32, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="preview",
            name="id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="preview",
            name="message_id",
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="shareablelink",
            name="id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="subtitle",
            name="attachment_id",
            field=models.CharField(
                db_index=True, max_length=32, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="subtitle",
            name="id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="subtitle",
            name="message_id",
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="thumbnail",
            name="attachment_id",
            field=models.CharField(
                db_index=True, max_length=32, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="thumbnail",
            name="id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="thumbnail",
            name="message_id",
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="userzip",
            name="id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
