# Generated by Django 4.2.18 on 2025-07-10 22:35

from django.db import migrations, models
import shortuuid.main
import shortuuidfield.fields


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0015_alter_file_id_alter_file_type_alter_folder_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fragment",
            name="channel_id",
            field=models.CharField(db_index=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="historicalthumbnail",
            name="channel_id",
            field=models.CharField(db_index=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="moment",
            name="channel_id",
            field=models.CharField(db_index=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="preview",
            name="channel_id",
            field=models.CharField(db_index=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="subtitle",
            name="channel_id",
            field=models.CharField(db_index=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="thumbnail",
            name="channel_id",
            field=models.CharField(db_index=True, max_length=32, null=True),
        ),

    ]
