# Generated by Django 4.2.18 on 2025-01-23 16:29

from django.db import migrations, models
import shortuuid.main
import shortuuidfield.fields


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0017_remove_historicalusersettings_discord_webhook_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="discordsettings",
            name="attachment_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="historicaldiscordsettings",
            name="attachment_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="discordsettings",
            name="channel_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="discordsettings",
            name="guild_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="file",
            name="id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="folder",
            name="id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="fragment",
            name="id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="historicaldiscordsettings",
            name="channel_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="historicaldiscordsettings",
            name="guild_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="historicalfile",
            name="id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                db_index=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
            ),
        ),
        migrations.AlterField(
            model_name="historicalfolder",
            name="id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                db_index=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
            ),
        ),
        migrations.AlterField(
            model_name="historicalfragment",
            name="id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                db_index=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
            ),
        ),
        migrations.AlterField(
            model_name="historicalpreview",
            name="id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                db_index=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
            ),
        ),
        migrations.AlterField(
            model_name="historicalthumbnail",
            name="id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                db_index=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
            ),
        ),
        migrations.AlterField(
            model_name="preview",
            name="id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="shareablelink",
            name="id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="thumbnail",
            name="id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="userzip",
            name="id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
