# Generated by Django 4.2.18 on 2025-07-10 23:25

import shortuuid.main
import shortuuidfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0017_populate_channel_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fragment",
            name="channel_id",
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="moment",
            name="channel_id",
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="preview",
            name="channel_id",
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="subtitle",
            name="channel_id",
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="thumbnail",
            name="channel_id",
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.DeleteModel(
            name="HistoricalThumbnail",
        ),
    ]
