# Generated by Django 4.2.18 on 2025-08-10 18:26

from django.db import migrations, models
import shortuuid.main
import shortuuidfield.fields


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0022_remove_perdevicetoken_revoked_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="perdevicetoken",
            name="city",
            field=models.CharField(default="Warsaw", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="perdevicetoken",
            name="country",
            field=models.CharField(default="Poland", max_length=100),
            preserve_default=False,
        ),
    ]
