# Generated by Django 4.2.18 on 2025-08-10 22:17

from django.db import migrations, models
import shortuuid.main
import shortuuidfield.fields


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0023_perdevicetoken_city_perdevicetoken_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="perdevicetoken",
            name="device_type",
            field=models.CharField(
                blank=True,
                choices=[("mobile", "Mobile"), ("pc", "PC"), ("code", "Code")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="perdevicetoken",
            name="city",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="perdevicetoken",
            name="country",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name="perdevicetoken",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("device_type__in", ["mobile", "pc", "code"]),
                    ("device_type__isnull", True),
                    _connector="OR",
                ),
                name="valid_device_type",
            ),
        ),
    ]
