# Generated by Django 4.2.18 on 2025-09-27 21:17

from django.db import migrations, models
import shortuuid.main
import shortuuidfield.fields


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0024_perdevicetoken_device_type_alter_file_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalusersettings",
            name="popup_preview",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="popup_preview",
            field=models.BooleanField(default=False),
        ),
    ]
