# Generated by Django 4.2.18 on 2025-12-06 20:02

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.main
import shortuuidfield.fields


class Migration(migrations.Migration):
    dependencies = [
        (
            "website",
            "0028_remove_auditentry_user_alter_file_id_alter_folder_id_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="file",
            name="valid_file_type",
        ),
        migrations.RemoveConstraint(
            model_name="moment",
            name="unique_file_timestamp",
        ),
        migrations.RenameField(
            model_name="channel",
            old_name="id",
            new_name="discord_id",
        ),
        migrations.RemoveField(
            model_name="historicalwebhook",
            name="id",
        ),
        migrations.RemoveField(
            model_name="webhook",
            name="id",
        ),
        migrations.AlterField(
            model_name="bot",
            name="id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="folder",
            name="id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="fragment",
            name="attachment_id",
            field=models.CharField(db_index=True, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name="fragment",
            name="id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="historicalbot",
            name="id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                db_index=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
            ),
        ),
        migrations.AlterField(
            model_name="historicalfile",
            name="id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                db_index=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
            ),
        ),
        migrations.AlterField(
            model_name="historicaltag",
            name="id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                db_index=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
            ),
        ),
        migrations.AlterField(
            model_name="historicalwebhook",
            name="discord_id",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="moment",
            name="attachment_id",
            field=models.CharField(db_index=True, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name="moment",
            name="id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="preview",
            name="attachment_id",
            field=models.CharField(db_index=True, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name="preview",
            name="id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="shareablelink",
            name="id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="subtitle",
            name="attachment_id",
            field=models.CharField(db_index=True, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name="subtitle",
            name="id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="thumbnail",
            name="attachment_id",
            field=models.CharField(db_index=True, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name="thumbnail",
            name="id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="userzip",
            name="id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="videoposition",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="webhook",
            name="channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="website.channel"
            ),
        ),
        migrations.AlterField(
            model_name="webhook",
            name="discord_id",
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name="bot",
            constraint=models.CheckConstraint(
                check=models.Q(("token__exact", ""), _negated=True),
                name="bot_token_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="bot",
            constraint=models.CheckConstraint(
                check=models.Q(("discord_id__regex", "^[0-9]{17,19}$")),
                name="bot_discord_id_snowflake_format",
            ),
        ),
        migrations.AddConstraint(
            model_name="bot",
            constraint=models.CheckConstraint(
                check=models.Q(("name__exact", ""), _negated=True),
                name="bot_name_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="channel",
            constraint=models.CheckConstraint(
                check=models.Q(("name__exact", ""), _negated=True),
                name="channel_name_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="channel",
            constraint=models.CheckConstraint(
                check=models.Q(("guild_id__regex", "^[0-9]{17,19}$")),
                name="channel_guild_id_snowflake_format",
            ),
        ),
        migrations.AddConstraint(
            model_name="channel",
            constraint=models.CheckConstraint(
                check=models.Q(("discord_id__regex", "^[0-9]{17,19}$")),
                name="channel_discord_id_snowflake_format",
            ),
        ),
        migrations.AddConstraint(
            model_name="discordsettings",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("guild_id__exact", ""),
                    ("guild_id__regex", "^[0-9]{17,19}$"),
                    _connector="OR",
                ),
                name="discordsettings_guild_id_valid_or_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="discordsettings",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("category_id__exact", ""),
                    ("category_id__regex", "^[0-9]{17,19}$"),
                    _connector="OR",
                ),
                name="discordsettings_category_id_valid_or_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="discordsettings",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("role_id__exact", ""),
                    ("role_id__regex", "^[0-9]{17,19}$"),
                    _connector="OR",
                ),
                name="discordsettings_role_id_valid_or_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="discordsettings",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("auto_setup_complete", False),
                    models.Q(("guild_id__exact", ""), _negated=True),
                    _connector="OR",
                ),
                name="discordsettings_guild_id_required_when_setup_complete",
            ),
        ),
        migrations.AddConstraint(
            model_name="discordsettings",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("auto_setup_complete", False),
                    models.Q(("category_id__exact", ""), _negated=True),
                    _connector="OR",
                ),
                name="discordsettings_category_id_required_when_setup_complete",
            ),
        ),
        migrations.AddConstraint(
            model_name="discordsettings",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("auto_setup_complete", False),
                    models.Q(("role_id__exact", ""), _negated=True),
                    _connector="OR",
                ),
                name="discordsettings_role_id_required_when_setup_complete",
            ),
        ),
        migrations.AddConstraint(
            model_name="discordsettings",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("auto_setup_complete", False),
                    models.Q(("attachment_name__exact", ""), _negated=True),
                    _connector="OR",
                ),
                name="discordsettings_attachment_name_required_when_setup_complete",
            ),
        ),
        migrations.AddConstraint(
            model_name="file",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "type__in",
                        [
                            "Video",
                            "Audio",
                            "Text",
                            "Document",
                            "Ebook",
                            "System",
                            "Database",
                            "Archive",
                            "Image",
                            "Executable",
                            "Code",
                            "Raw image",
                            "Other",
                        ],
                    )
                ),
                name="file_valid_file_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="folder",
            constraint=models.CheckConstraint(
                check=models.Q(("name__regex", "^\\s*$"), _negated=True),
                name="folder_name_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="folder",
            constraint=models.CheckConstraint(
                check=models.Q(("last_modified_at__gte", models.F("created_at"))),
                name="folder_last_modified_after_created",
            ),
        ),
        migrations.AddConstraint(
            model_name="folder",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("inTrash", False), ("inTrashSince__isnull", True)),
                    models.Q(("inTrash", True), ("inTrashSince__isnull", False)),
                    _connector="OR",
                ),
                name="folder_trash_consistent",
            ),
        ),
        migrations.AddConstraint(
            model_name="folder",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("lockFrom__isnull", True), ("password__isnull", True)),
                    models.Q(("lockFrom__isnull", False), ("password__isnull", False)),
                    _connector="OR",
                ),
                name="folder_lock_password_consistent",
            ),
        ),
        migrations.AddConstraint(
            model_name="folder",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("lockFrom__isnull", False), ("autoLock", False), _connector="OR"
                ),
                name="folder_autoLock_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="folder",
            constraint=models.CheckConstraint(
                check=models.Q(("id", models.F("parent")), _negated=True),
                name="folder_parent_not_self",
            ),
        ),
        migrations.AddConstraint(
            model_name="fragment",
            constraint=models.CheckConstraint(
                check=models.Q(("sequence__gt", 0)),
                name="fragment_sequence_greater_than_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="fragment",
            constraint=models.CheckConstraint(
                check=models.Q(("offset__gte", 0)), name="fragment_offset_non_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="fragment",
            constraint=models.UniqueConstraint(
                fields=("file", "sequence"),
                name="fragment_fragment_unique_sequence_per_file",
            ),
        ),
        migrations.AddConstraint(
            model_name="fragment",
            constraint=models.UniqueConstraint(
                fields=("file", "offset"),
                name="fragment_fragment_unique_offset_per_file",
            ),
        ),
        migrations.AddConstraint(
            model_name="moment",
            constraint=models.UniqueConstraint(
                fields=("file", "timestamp"), name="moment_unique_file_timestamp"
            ),
        ),
        migrations.AddConstraint(
            model_name="moment",
            constraint=models.CheckConstraint(
                check=models.Q(("timestamp__gte", 0)),
                name="moment_timestamp_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="moment",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("key__isnull", True), ("iv__isnull", True)),
                    models.Q(("key__isnull", False), ("iv__isnull", False)),
                    _connector="OR",
                ),
                name="moment_iv_key_consistent",
            ),
        ),
        migrations.AddConstraint(
            model_name="perdevicetoken",
            constraint=models.CheckConstraint(
                check=models.Q(("token_hash__exact", ""), _negated=True),
                name="perdevicetoken_token_hash_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="perdevicetoken",
            constraint=models.CheckConstraint(
                check=models.Q(("device_id__exact", ""), _negated=True),
                name="perdevicetoken_device_id_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="perdevicetoken",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("expires_at__isnull", True),
                    ("expires_at__gte", models.F("created_at")),
                    _connector="OR",
                ),
                name="perdevicetoken_expires_after_created",
            ),
        ),
        migrations.AddConstraint(
            model_name="perdevicetoken",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("last_used_at__isnull", True),
                    ("last_used_at__gte", models.F("created_at")),
                    _connector="OR",
                ),
                name="perdevicetoken_last_used_after_created",
            ),
        ),
        migrations.AddConstraint(
            model_name="perdevicetoken",
            constraint=models.UniqueConstraint(
                fields=("user", "device_id"),
                name="perdevicetoken_unique_device_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="perdevicetoken",
            constraint=models.UniqueConstraint(
                fields=("user", "token_hash"),
                name="perdevicetoken_unique_token_hash_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="preview",
            constraint=models.CheckConstraint(
                check=models.Q(("encrypted_size__gte", 0)),
                name="preview_encrypted_size_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="preview",
            constraint=models.CheckConstraint(
                check=models.Q(("key__isnull", False)), name="preview_key_required"
            ),
        ),
        migrations.AddConstraint(
            model_name="shareablelink",
            constraint=models.CheckConstraint(
                check=models.Q(("token__exact", ""), _negated=True),
                name="shareablelink_token_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="shareablelink",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("password__isnull", True),
                    models.Q(("password__exact", ""), _negated=True),
                    _connector="OR",
                ),
                name="shareablelink_password_not_empty_string",
            ),
        ),
        migrations.AddConstraint(
            model_name="subtitle",
            constraint=models.CheckConstraint(
                check=models.Q(("language__exact", ""), _negated=True),
                name="subtitle_language_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="subtitle",
            constraint=models.UniqueConstraint(
                fields=("file", "language"), name="subtitle_unique_language_per_file"
            ),
        ),
        migrations.AddConstraint(
            model_name="subtitle",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("key__isnull", True), ("iv__isnull", True)),
                    models.Q(("key__isnull", False), ("iv__isnull", False)),
                    _connector="OR",
                ),
                name="subtitle_encryption_fields_consistent",
            ),
        ),
        migrations.AddConstraint(
            model_name="thumbnail",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("iv__isnull", True), ("key__isnull", True)),
                    models.Q(("iv__isnull", False), ("key__isnull", False)),
                    _connector="OR",
                ),
                name="thumbnail_iv_key_consistent",
            ),
        ),
        migrations.AddConstraint(
            model_name="videoposition",
            constraint=models.CheckConstraint(
                check=models.Q(("timestamp__gte", 0)),
                name="videoposition_timestamp_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="webhook",
            constraint=models.CheckConstraint(
                check=models.Q(("discord_id__exact", ""), _negated=True),
                name="webhook_discord_id_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="webhook",
            constraint=models.CheckConstraint(
                check=models.Q(("url__exact", ""), _negated=True),
                name="webhook_url_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="webhook",
            constraint=models.CheckConstraint(
                check=models.Q(("guild_id__regex", "^[0-9]{17,19}$")),
                name="webhook_guild_id_snowflake_format",
            ),
        ),
        migrations.AddConstraint(
            model_name="webhook",
            constraint=models.CheckConstraint(
                check=models.Q(("discord_id__regex", "^[0-9]{17,19}$")),
                name="webhook_discord_id_snowflake_format",
            ),
        ),
        migrations.AddConstraint(
            model_name="webhook",
            constraint=models.CheckConstraint(
                check=models.Q(("name__exact", ""), _negated=True),
                name="webhook_name_not_empty",
            ),
        ),
    ]
