name: Build

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    # 1 Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2 Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # 3 Log in to GitHub Container Registry
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.MY_GITHUB_TOKEN }}

    - name: Build & Push Backend Image
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/idrive-backend:latest
        cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/idrive-backend:cache
        cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/idrive-backend:cache,mode=max


    - name: Build & Push Nginx Image
      uses: docker/build-push-action@v4
      with:
        context: ./frontend
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/idrive-nginx:latest
        cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/idrive-nginx:cache
        cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/idrive-nginx:cache,mode=max

