name: Build

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    # 1. Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # 3. Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 5. Logs to GitHub Container Registry
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.MY_GITHUB_TOKEN }} # GitHub Token for authentication

      # 6. Build and push the Docker images using docker-compose
    - name: Build and push Docker images
      run: |
        apt-get update && apt-get install -y --no-install-recommends build-essential
        docker compose build 

      # 7. Tag and push Backend to GitHub Container Registry
    - name: Tag and push Backend to GitHub Container Registry
      run: |
        docker images -a
        docker push ghcr.io/${{ github.repository_owner }}/idrive-backend:latest

    # 8. Tag and push Nginx to GitHub Container Registry
    - name: Tag and push Nginx to GitHub Container Registry
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/idrive-nginx:latest