name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # 3. Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 4. Set env file for Frontend
    - name: Set env file for Frontend
      run : |
        ls
        cd frontend
        echo "VITE_BACKEND_BASE_WS=wss://${{ secrets.DEPLOYMENT_HOST }}/api" > .env
        echo "VITE_BACKEND_BASE_URL=https://${{ secrets.DEPLOYMENT_HOST }}/api" >> .env
        echo "aaaa"
        ls -a

      # 4. Set env file for Backend
    - name: Set env file for Backend
      run: |
        ls -a
        cd backend
        echo "IS_DEV_ENV=False" >> .env 
        echo "DEPLOYMENT_HOST=${{ secrets.DEPLOYMENT_HOST }}" >> .env
        
        echo "I_DRIVE_BACKEND_SECRET_KEY=${{ secrets.DJANGO_BACKEND_SECRET_KEY }}" >> .env
        
        echo "DISCORD_TOKEN1=${{ secrets.DISCORD_TOKEN1 }}" >> .env
        echo "DISCORD_TOKEN2=${{ secrets.DISCORD_TOKEN2 }}" >> .env
        echo "DISCORD_TOKEN3=${{ secrets.DISCORD_TOKEN3 }}" >> .env
        echo "DISCORD_TOKEN4=${{ secrets.DISCORD_TOKEN4 }}" >> .env
        echo "DISCORD_TOKEN5=${{ secrets.DISCORD_TOKEN5 }}" >> .env
        echo "DISCORD_TOKEN6=${{ secrets.DISCORD_TOKEN6 }}" >> .env
        echo "DISCORD_TOKEN7=${{ secrets.DISCORD_TOKEN7 }}" >> .env
        echo "DISCORD_TOKEN8=${{ secrets.DISCORD_TOKEN8 }}" >> .env
        echo "DISCORD_TOKEN9=${{ secrets.DISCORD_TOKEN9 }}" >> .env
        echo "DISCORD_TOKEN10=${{ secrets.DISCORD_TOKEN10 }}" >> .env
        
        echo "CORS_FRONTEND=frontend" >> .env
        echo "CORS_FRONTEND_PORT=5173" >> .env
        
        echo "I_DRIVE_REDIS_ADDRESS=redis" >> .env
        echo "I_DRIVE_REDIS_PORT=6379" >> .env
        
        echo "BACKEND_BASE_URL=https://${{ secrets.DEPLOYMENT_HOST }}/api" >> .env
        
        echo "I_DRIVE_BACKEND_STORAGE_DIR=/app/data" >> .env

      # 5. Build and push the Docker images using docker-compose
    - name: Build and push Docker images
      run: |
        ls -a
        docker compose build
        docker compose push
