name: Build

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    # 1. Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # 3. Cache Docker layers
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile', '**/frontend/package-lock.json', '**/backend/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-docker-
        

    # 3. Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 4. Set env file for Frontend
    - name: Set env file for Frontend
      run : |
        cd frontend
        echo "VITE_BACKEND_BASE_WS=wss://${{ secrets.DEPLOYMENT_HOST }}/api" > .env
        echo "VITE_BACKEND_BASE_URL=https://${{ secrets.DEPLOYMENT_HOST }}/api" >> .env

    # 5. Login to GitHub Container Registry
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.MY_GITHUB_TOKEN }} # GitHub Token for authentication

    - name: build docker image
      run: >
        docker buildx build 
        --file docker-compose.yml
        --cache-from "type=local,src=$GITHUB_WORKSPACE/cache"
        --cache-to "type=local,dest=$GITHUB_WORKSPACE/cache"
        

      # 7. Tag and push Backend to GitHub Container Registry
    - name: Tag and push Backend to GitHub Container Registry
      run: |
        docker images -a
        docker tag ${{ github.repository_owner }}/backend:latest ghcr.io/${{ github.repository_owner }}/idrive-backend:latest
        docker push ghcr.io/${{ github.repository_owner }}/idrive-backend:latest

      # 8. Tag and push Nginx to GitHub Container Registry
    - name: Tag and push Nginx to GitHub Container Registry
      run: |
        docker tag nginx:latest ghcr.io/${{ github.repository_owner }}/idrive-nginx:latest
        docker tag ${{ github.repository_owner }}/nginx:latest ghcr.io/${{ github.repository_owner }}/idrive-nginx:latest
        docker push ghcr.io/${{ github.repository_owner }}/idrive-nginx:latest