name: build and deploy

on:
  workflow_dispatch:

permissions:
  packages: write
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build.yml

  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yml