name: Deploy App

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # SSH into the server and execute commands
    - name: Deploy to Virtual Machine
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.CI_DEPLOYMENT_HOST }}
        port: ${{ secrets.CI_DEPLOYMENT_PORT }}
        username: ${{ secrets.CI_RPI_USERNAME }}
        key: ${{ secrets.CI_RPI_SSH_KEY }}
        script: |
          echo "Pulling the latest Docker image..."
          docker pull ${{ secrets.DOCKER_IMAGE }}

          echo "Stopping and removing existing containers (if any)..."
          docker stop myapp || true
          docker rm myapp || true

          echo "Starting new container..."
          docker run -d --name myapp -p 80:80 ${{ secrets.DOCKER_IMAGE }}

          echo "Deployment completed!"
