name: Deploy App

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # SSH into the server and execute commands
    - name: Deploy to Virtual Machine
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.CI_DEPLOYMENT_HOST }}
        port: ${{ secrets.CI_DEPLOYMENT_PORT }}
        username: ${{ secrets.CI_RPI_USERNAME }}
        key: ${{ secrets.CI_RPI_SSH_KEY }}
        script: |
          
          echo "Logging in to GitHub Container Registry..."
          echo "${{ secrets.MY_GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
          
          
          echo "navigating to idrive"

          mkdir -p idrive
          cd idrive
          echo "Pulling docker-compose.yml..."
          curl -O https://raw.githubusercontent.com/pam-param-pam/I-Drive/refs/heads/master/docker-compose.yml?token=GHSAT0AAAAAACYQHJIESLJUDXKOIMXYLSVGZYCUKMA
          mv 'docker-compose.yml?token=GHSAT0AAAAAACYQHJIESLJUDXKOIMXYLSVGZYCUKMA' docker-compose.yml

          ls -a
          docker compose pull
          docker compose up

         
